### ISSUE TITLE
Allow cyrillic letters in book names

### ISSUE THREAD

**Issue by anareaty** [lenalebt/obsidian-pocketbook-cloud-highlight-importer#4]
Right now if the book name is in cyrillic alphabet, book folder is created with an empty name. It can be easily fixed, you just need replace this line:

```
const sanitized_book_title = book.title.replace(/[^a-zA-Z0-9 -]/g, "");
```

with this:

```
const sanitized_book_title = book.title.replace(/[^a-zA-Zа-яА-ЯёЁ0-9 -]/g, "");
```

It would probably be useful to add some other alphabets symbols too.

**Comment by lenalebt** [comment]
Probably the same as in #3 . I'll have a look :-)

**Comment by lenalebt** [comment]
Should be working in 0.1.6 now, I switched from an allowlist of characters to a blocklist, which should address my fear of using disallowed characters for some file systems :-). Feel free to reopen if the issue persists somehow.
